language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - nightly
  - pypy
  - pypy3
matrix:
  include:
    - name: flake8
      install: pip install flake8
      script: flake8 *.py
      after_success:
install:
  - pip install coverage coveralls
script:
  - coverage run --source=profilehooks test_profilehooks.py
after_success:
  - coveralls
notifications:
  email: false
